
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 24 13:31:17 CDT 2017
//----------------------------------------------------

package arduino;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OPERADOR_ARITMETICO = 2;
  public static final int error = 1;
  public static final int NUMBER = 3;
  public static final int EOF = 0;
}

