
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Apr 27 14:32:48 CDT 2017
//----------------------------------------------------

package arduino;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHILE = 12;
  public static final int PCOMA = 2;
  public static final int FOR = 14;
  public static final int MENOS = 4;
  public static final int PARENI = 7;
  public static final int NUMBER = 15;
  public static final int LLAVEI = 9;
  public static final int POR = 5;
  public static final int ENTRE = 6;
  public static final int PAREND = 8;
  public static final int EOF = 0;
  public static final int MAS = 3;
  public static final int IF = 11;
  public static final int LLAVED = 10;
  public static final int ID = 16;
  public static final int error = 1;
  public static final int DO = 13;
}

