
package Analizador;

public enum Tokens {
    TIPO_DATO, CLASE_CADENA_CARACTERES, DECLARACION_METODO,
    CONSTANTE_BOOLEANA, COMPARADOR_OR, COMPARADOR_AND,
    ESTRUCTURA_CONTROL, OPERADOR, SUPERCLASE, IMPORTAR_PAQUETE,
    IMPORTAR_COMPONENTE_SWING, PALABRA_RESERVADA, DECLARACION_CLASE,
    ESCAPE_COMENTARIO, COMPARADOR, LLAMADA_METODO, ESTRUCTURA_WHILE,
    FOR_MEJORADO;
}//end enum