/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebaa;

/**
 *
 * @author Mary
 */
public enum Token {
    IDENTIFICADOR, LIBRERIA, OPERADOR_ARITMETICO,OPERADOR_ASIGNACION,
    OPERADOR_COMPARACION,OPERADOR_BOOLEANO,OPERADOR_INCREMENTO, OPERADOR_DECREMENTO, 
    OPERADOR_COMPUESTO,OPERADOR_BIT,ESTRUCTURAS_DE_CONTROL,CONSTANTE,
    BOOLEANO,TIPO_DE_DATO, CALIFICADOR, DELIMITADOR,
    PRINCIPIO_FUNCION,FINAL_FUNCION,FUNCION_TIEMPO,ESTRUCTURA_INICIO_EJECUCION, METODO, INT,
    FUNCION_ES_DIGITAL,FUNCION_ES_ANALOGICA,PARENTESIS, ERROR_LEXICO
}
